from ixnetwork_restpy import SessionAssistant
import time

final_table = []
apiServerIp = '10.36.74.13'

session = SessionAssistant(IpAddress=apiServerIp, RestPort=None, UserName='admin', Password='admin', 
                            SessionName=None, SessionId=1, ApiKey=None,
                            ClearConfig=False)


flow_stats_view = session.Ixnetwork.Statistics.find().View.find(Caption = "Flow Statistics" )
# We are getting the drilldown here. Arg2 = Row Number in view and Arg3 is value in the dropdown
flow_stats_drill_down_for_uds = flow_stats_view.DoDrillDownByOption(Arg2=1, Arg3='Ethernet:Outer VLAN ID (4 bits) at offset 124') # 'Show All Egress'

time.sleep(30) # When we do drill down on Flow Statistics it takes some time for User def stats to populate.

# Now we have a tab for User Defined Statistics lets get values from that
uds_view = session.Ixnetwork.Statistics.find().View.find(Caption = "User Defined Statistics")
# Select the option for Arg2 based on the packets you want to view
uds_view.SetEgressViewMode(Arg2="kAll") # (kAll | kNotDefined | kRowsWithNoPackets | kRowsWithPackets)

final_table.append(uds_view.Data.ColumnCaptions)
for item in uds_view.Data.PageValues[0]:
    final_table.append(item)

# Making a dict of the values for ease of parsing
# Step 1: Extract the keys (column headers)
keys = final_table[0]  # First row is the header
# Step 2: Convert to a list of dictionaries
result = [dict(zip(keys, row)) for row in final_table[1:]]  # Skip the header row
print(result)


"""
Sample Output:
==============

[
    {
        "Tx Port": "Ethernet - 001",
        "Rx Port": "Ethernet - 002",
        "Traffic Item": "Traffic Item 1",
        "Egress Tracking": "Ethernet:Outer VLAN ID (4 bits) at offset 124",
        "Tx Frames": "33755781474",
        "Rx Frames": "33755781231",
        "Frames Delta": "243",
        "Loss %": "0",
        "Tx Frame Rate": "111111111",
        "Rx Frame Rate": "111111111.5",
        "Tx L1 Rate (bps)": "79999999920",
        "Rx L1 Rate (bps)": "80000000280",
        "Tx L1 Rate (Gbps)": "80",
        "Rx L1 Rate (Gbps)": "80",
        "Rx Bytes": "2362904686170",
        "Tx Rate (Bps)": "7777777770",
        "Rx Rate (Bps)": "7777777805",
        "Tx Rate (bps)": "62222222160",
        "Rx Rate (bps)": "62222222440",
        "Tx Rate (Kbps)": "62222222.16",
        "Rx Rate (Kbps)": "62222222.44",
        "Tx Rate (Mbps)": "62222.222",
        "Rx Rate (Mbps)": "62222.222",
        "Tx Rate (Gbps)": "62.222",
        "Rx Rate (Gbps)": "62.222",
        "Store-Forward Avg Latency (ns)": "120",
        "Store-Forward Min Latency (ns)": "114",
        "Store-Forward Max Latency (ns)": "125",
        "First TimeStamp": "00:00:00.309",
        "Last TimeStamp": "00:05:04.111"
    },
    {
        "Tx Port": "",
        "Rx Port": "",
        "Traffic Item": "",
        "Egress Tracking": "0",
        "Tx Frames": "",
        "Rx Frames": "0",
        "Frames Delta": "",
        "Loss %": "",
        "Tx Frame Rate": "",
        "Rx Frame Rate": "0",
        "Tx L1 Rate (bps)": "",
        "Rx L1 Rate (bps)": "0",
        "Tx L1 Rate (Gbps)": "",
        "Rx L1 Rate (Gbps)": "0",
        "Rx Bytes": "0",
        "Tx Rate (Bps)": "",
        "Rx Rate (Bps)": "0",
        "Tx Rate (bps)": "",
        "Rx Rate (bps)": "0",
        "Tx Rate (Kbps)": "",
        "Rx Rate (Kbps)": "0",
        "Tx Rate (Mbps)": "",
        "Rx Rate (Mbps)": "0",
        "Tx Rate (Gbps)": "",
        "Rx Rate (Gbps)": "0",
        "Store-Forward Avg Latency (ns)": "",
        "Store-Forward Min Latency (ns)": "",
        "Store-Forward Max Latency (ns)": "",
        "First TimeStamp": "00:00:00.000",
        "Last TimeStamp": "00:00:00.000"
    },
    {
        "Tx Port": "",
        "Rx Port": "",
        "Traffic Item": "",
        "Egress Tracking": "1",
        "Tx Frames": "",
        "Rx Frames": "33755781231",
        "Frames Delta": "",
        "Loss %": "",
        "Tx Frame Rate": "",
        "Rx Frame Rate": "111111111.5",
        "Tx L1 Rate (bps)": "",
        "Rx L1 Rate (bps)": "80000000280",
        "Tx L1 Rate (Gbps)": "",
        "Rx L1 Rate (Gbps)": "80",
        "Rx Bytes": "2362904686170",
        "Tx Rate (Bps)": "",
        "Rx Rate (Bps)": "7777777805",
        "Tx Rate (bps)": "",
        "Rx Rate (bps)": "62222222440",
        "Tx Rate (Kbps)": "",
        "Rx Rate (Kbps)": "62222222.44",
        "Tx Rate (Mbps)": "",
        "Rx Rate (Mbps)": "62222.222",
        "Tx Rate (Gbps)": "",
        "Rx Rate (Gbps)": "62.222",
        "Store-Forward Avg Latency (ns)": "120",
        "Store-Forward Min Latency (ns)": "114",
        "Store-Forward Max Latency (ns)": "125",
        "First TimeStamp": "00:00:00.309",
        "Last TimeStamp": "00:05:04.111"
    },
    {
        "Tx Port": "",
        "Rx Port": "",
        "Traffic Item": "",
        "Egress Tracking": "2",
        "Tx Frames": "",
        "Rx Frames": "0",
        "Frames Delta": "",
        "Loss %": "",
        "Tx Frame Rate": "",
        "Rx Frame Rate": "0",
        "Tx L1 Rate (bps)": "",
        "Rx L1 Rate (bps)": "0",
        "Tx L1 Rate (Gbps)": "",
        "Rx L1 Rate (Gbps)": "0",
        "Rx Bytes": "0",
        "Tx Rate (Bps)": "",
        "Rx Rate (Bps)": "0",
        "Tx Rate (bps)": "",
        "Rx Rate (bps)": "0",
        "Tx Rate (Kbps)": "",
        "Rx Rate (Kbps)": "0",
        "Tx Rate (Mbps)": "",
        "Rx Rate (Mbps)": "0",
        "Tx Rate (Gbps)": "",
        "Rx Rate (Gbps)": "0",
        "Store-Forward Avg Latency (ns)": "",
        "Store-Forward Min Latency (ns)": "",
        "Store-Forward Max Latency (ns)": "",
        "First TimeStamp": "00:00:00.000",
        "Last TimeStamp": "00:00:00.000"
    },
    {
        "Tx Port": "",
        "Rx Port": "",
        "Traffic Item": "",
        "Egress Tracking": "3",
        "Tx Frames": "",
        "Rx Frames": "0",
        "Frames Delta": "",
        "Loss %": "",
        "Tx Frame Rate": "",
        "Rx Frame Rate": "0",
        "Tx L1 Rate (bps)": "",
        "Rx L1 Rate (bps)": "0",
        "Tx L1 Rate (Gbps)": "",
        "Rx L1 Rate (Gbps)": "0",
        "Rx Bytes": "0",
        "Tx Rate (Bps)": "",
        "Rx Rate (Bps)": "0",
        "Tx Rate (bps)": "",
        "Rx Rate (bps)": "0",
        "Tx Rate (Kbps)": "",
        "Rx Rate (Kbps)": "0",
        "Tx Rate (Mbps)": "",
        "Rx Rate (Mbps)": "0",
        "Tx Rate (Gbps)": "",
        "Rx Rate (Gbps)": "0",
        "Store-Forward Avg Latency (ns)": "",
        "Store-Forward Min Latency (ns)": "",
        "Store-Forward Max Latency (ns)": "",
        "First TimeStamp": "00:00:00.000",
        "Last TimeStamp": "00:00:00.000"
    },
    {
        "Tx Port": "",
        "Rx Port": "",
        "Traffic Item": "",
        "Egress Tracking": "4",
        "Tx Frames": "",
        "Rx Frames": "0",
        "Frames Delta": "",
        "Loss %": "",
        "Tx Frame Rate": "",
        "Rx Frame Rate": "0",
        "Tx L1 Rate (bps)": "",
        "Rx L1 Rate (bps)": "0",
        "Tx L1 Rate (Gbps)": "",
        "Rx L1 Rate (Gbps)": "0",
        "Rx Bytes": "0",
        "Tx Rate (Bps)": "",
        "Rx Rate (Bps)": "0",
        "Tx Rate (bps)": "",
        "Rx Rate (bps)": "0",
        "Tx Rate (Kbps)": "",
        "Rx Rate (Kbps)": "0",
        "Tx Rate (Mbps)": "",
        "Rx Rate (Mbps)": "0",
        "Tx Rate (Gbps)": "",
        "Rx Rate (Gbps)": "0",
        "Store-Forward Avg Latency (ns)": "",
        "Store-Forward Min Latency (ns)": "",
        "Store-Forward Max Latency (ns)": "",
        "First TimeStamp": "00:00:00.000",
        "Last TimeStamp": "00:00:00.000"
    },
    {
        "Tx Port": "",
        "Rx Port": "",
        "Traffic Item": "",
        "Egress Tracking": "5",
        "Tx Frames": "",
        "Rx Frames": "0",
        "Frames Delta": "",
        "Loss %": "",
        "Tx Frame Rate": "",
        "Rx Frame Rate": "0",
        "Tx L1 Rate (bps)": "",
        "Rx L1 Rate (bps)": "0",
        "Tx L1 Rate (Gbps)": "",
        "Rx L1 Rate (Gbps)": "0",
        "Rx Bytes": "0",
        "Tx Rate (Bps)": "",
        "Rx Rate (Bps)": "0",
        "Tx Rate (bps)": "",
        "Rx Rate (bps)": "0",
        "Tx Rate (Kbps)": "",
        "Rx Rate (Kbps)": "0",
        "Tx Rate (Mbps)": "",
        "Rx Rate (Mbps)": "0",
        "Tx Rate (Gbps)": "",
        "Rx Rate (Gbps)": "0",
        "Store-Forward Avg Latency (ns)": "",
        "Store-Forward Min Latency (ns)": "",
        "Store-Forward Max Latency (ns)": "",
        "First TimeStamp": "00:00:00.000",
        "Last TimeStamp": "00:00:00.000"
    },
    {
        "Tx Port": "",
        "Rx Port": "",
        "Traffic Item": "",
        "Egress Tracking": "6",
        "Tx Frames": "",
        "Rx Frames": "0",
        "Frames Delta": "",
        "Loss %": "",
        "Tx Frame Rate": "",
        "Rx Frame Rate": "0",
        "Tx L1 Rate (bps)": "",
        "Rx L1 Rate (bps)": "0",
        "Tx L1 Rate (Gbps)": "",
        "Rx L1 Rate (Gbps)": "0",
        "Rx Bytes": "0",
        "Tx Rate (Bps)": "",
        "Rx Rate (Bps)": "0",
        "Tx Rate (bps)": "",
        "Rx Rate (bps)": "0",
        "Tx Rate (Kbps)": "",
        "Rx Rate (Kbps)": "0",
        "Tx Rate (Mbps)": "",
        "Rx Rate (Mbps)": "0",
        "Tx Rate (Gbps)": "",
        "Rx Rate (Gbps)": "0",
        "Store-Forward Avg Latency (ns)": "",
        "Store-Forward Min Latency (ns)": "",
        "Store-Forward Max Latency (ns)": "",
        "First TimeStamp": "00:00:00.000",
        "Last TimeStamp": "00:00:00.000"
    },
    {
        "Tx Port": "",
        "Rx Port": "",
        "Traffic Item": "",
        "Egress Tracking": "7",
        "Tx Frames": "",
        "Rx Frames": "0",
        "Frames Delta": "",
        "Loss %": "",
        "Tx Frame Rate": "",
        "Rx Frame Rate": "0",
        "Tx L1 Rate (bps)": "",
        "Rx L1 Rate (bps)": "0",
        "Tx L1 Rate (Gbps)": "",
        "Rx L1 Rate (Gbps)": "0",
        "Rx Bytes": "0",
        "Tx Rate (Bps)": "",
        "Rx Rate (Bps)": "0",
        "Tx Rate (bps)": "",
        "Rx Rate (bps)": "0",
        "Tx Rate (Kbps)": "",
        "Rx Rate (Kbps)": "0",
        "Tx Rate (Mbps)": "",
        "Rx Rate (Mbps)": "0",
        "Tx Rate (Gbps)": "",
        "Rx Rate (Gbps)": "0",
        "Store-Forward Avg Latency (ns)": "",
        "Store-Forward Min Latency (ns)": "",
        "Store-Forward Max Latency (ns)": "",
        "First TimeStamp": "00:00:00.000",
        "Last TimeStamp": "00:00:00.000"
    }
]


"""
